print("=== HEALTHCARE WORKERS LOGIN CREDENTIALS ===")
print()
print("1. Dr. Test Healthcare")
print("   Email: doctor@expertease.com")
print("   Password: 123456")
print("   Specialization: General Medicine")
print()
print("2. Niharika Rothe")
print("   Email: co2023.niharika.rothe@ves.ac.in")
print("   Password: 123456")
print("   Specialization: Dentist")
print()
print("3. Aarohi Gate")
print("   Email: aarohigate01@gmail.com")
print("   Password: 123456")
print("   Specialization: Dermatologist")
print()
print("4. goat")
print("   Email: pro@gmail.com")
print("   Password: 123456")
print("   Specialization: eye")
print()
print("All healthcare workers can now login at:")
print("/worker/healthcare/login")
print()
print("Patients can book appointments at:")
print("/healthcare/book/{doctor_id}")
