print("=== TESTING FRONTEND BOOKING FLOW ===")
print()
print("1. Go to: http://localhost:3000/healthcare/book/6")
print("2. The page should:")
print("   - Show Dr. Test Healthcare details")
print("   - Have today's date selected by default")
print("   - Show available time slots (should be 12 slots for today)")
print("   - Allow you to select a time slot")
print("   - Allow you to book an appointment")
print()
print("3. Check browser console for debug logs:")
print("   - 'Date selected: YYYY-MM-DD'")
print("   - 'Fetching slots for doctor 6 on date YYYY-MM-DD'")
print("   - 'Response status: 200'")
print("   - 'Available slots: [...]'")
print()
print("4. If time slots don't appear:")
print("   - Check network tab in browser dev tools")
print("   - Look for the API call to /healthcare/availability/6")
print("   - Check if it returns 200 status")
print()
print("Expected API response:")
print('{"available_slots": ["09:00 AM", "09:30 AM", "10:00 AM", ...]}')
print()
print("Current date for testing: 2026-04-13")
